In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import mglearn

### Encoding 
###### converting the string of an attribute into numerical values for more accurate results in models
###### this can be done in 3 ways :
###### 1. One Hot Encoding(OHE)/Nominal Encoding


### One Hot Encoding

In [31]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

encoded = encoder.fit_transform(iris[['species']]).toarray()


In [ ]:
# make a df of the encoded values

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['species']))
encoded_df.head()

species_setosa  species_versicolor  species_virginica
0             1.0                 0.0                0.0
1             1.0                 0.0                0.0
2             1.0                 0.0                0.0
3             1.0                 0.0                0.0
4             1.0                 0.0                0.0

In [32]:
#merge and drop the the original column from which we made the one hot encoding df.

df_final = pd.concat([iris.drop("species",axis=1).reset_index(drop=True),encoded_df.reset_index(drop=True)],axis =1)

In [21]:
df_final.head()

sepal_length  sepal_width  petal_length  petal_width  species_setosa  \
0           5.1          3.5           1.4          0.2             1.0   
1           4.9          3.0           1.4          0.2             1.0   
2           4.7          3.2           1.3          0.2             1.0   
3           4.6          3.1           1.5          0.2             1.0   
4           5.0          3.6           1.4          0.2             1.0   

   species_versicolor  species_virginica  
0                 0.0                0.0  
1                 0.0                0.0  
2                 0.0                0.0  
3                 0.0                0.0  
4                 0.0                0.0

### Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
label.fit_transform(iris[['species']])

/Users/pranaya/opt/miniconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
label.transform(['versicolor'])

array([1])

In [33]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
iris['species_code'] = label.fit_transform(iris[['species']])

/Users/pranaya/opt/miniconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [36]:
iris.tail(10)

sepal_length  sepal_width  petal_length  petal_width    species  \
140           6.7          3.1           5.6          2.4  virginica   
141           6.9          3.1           5.1          2.3  virginica   
142           5.8          2.7           5.1          1.9  virginica   
143           6.8          3.2           5.9          2.3  virginica   
144           6.7          3.3           5.7          2.5  virginica   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_code  
140             2  
141             2  
142             2  
143             2  
144             2  
145             2  
146             2  
147             2  
148             2  
149             2

In [37]:
iris.drop('species',axis=1,inplace=True)

In [38]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species_code
0           5.1          3.5           1.4          0.2             0
1           4.9          3.0           1.4          0.2             0
2           4.7          3.2           1.3          0.2             0
3           4.6          3.1           1.5          0.2             0
4           5.0          3.6           1.4          0.2             0

### Ordinal Encoding

In [43]:
from sklearn.preprocessing import OrdinalEncoder


In [40]:
df = pd.DataFrame({'size':['Small','Medium','Large','Medium','Small','Large']})

In [42]:
df

size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large

In [44]:
ordinal = OrdinalEncoder(categories=[['Small','Medium','Large']])

In [45]:
ordinal.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [47]:
ordinal.transform([['Medium']])

/Users/pranaya/opt/miniconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])